// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package totdb

import (
	"time"
)

type Tally struct {
	ID        int64
	TotID     string
	CreatedAt time.Time
	Kind      string
}

type Tot struct {
	ID       string
	Name     string
	Timezone string
}
