// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package totdb

import (
	"time"
)

type Baby struct {
	ID       string
	Name     string
	Timezone string
}

type Feed struct {
	ID        int64
	BabyID    string
	CreatedAt time.Time
	FeedType  int64
	Ounces    int64
}

type Soil struct {
	ID        int64
	BabyID    string
	CreatedAt time.Time
	Wet       int64
	Soil      int64
}
